---
- name: Enable ldap config
  command: >
    /usr/local/openvpn_as/scripts/sacli
    --key "auth.module.type" --value "ldap" ConfigPut
  when: >
    jsondata_config | json_query('\"auth.module.type\"') != "ldap"
- name: Set LDAP Name
  command: >
    /usr/local/openvpn_as/scripts/sacli
    --key "auth.ldap.0.name" --value {{ ldap_realm }} ConfigPut
  when: >
    jsondata_config | json_query('\"auth.ldap.0.name\"') != ldap_realm
- name: Set LDAP Server
  command: >
    /usr/local/openvpn_as/scripts/sacli
    --key "auth.ldap.0.server.0.host" --value "{{ ldap_server }}" ConfigPut
  when: >
    jsondata_config | json_query('\"auth.ldap.0.server.0.host\"') != ldap_server
- name: Set LDAP BIND DN
  command: >
    /usr/local/openvpn_as/scripts/sacli
    --key "auth.ldap.0.bind_dn" --value "{{ ldap_bind_dn }}" ConfigPut
  when: >
    jsondata_config | json_query('\"auth.ldap.0.bind_dn\"') != ldap_bind_dn
- name: Set LDAP BIND DN Password
  command: >
    /usr/local/openvpn_as/scripts/sacli
    --key "auth.ldap.0.bind_pw" --value {{ ldap_bind_pw }} ConfigPut
  when: >
    jsondata_config | json_query('\"auth.ldap.0.bind_pw\"') != ldap_bind_pw
- name: Set LDAP User base DN
  command: >
    /usr/local/openvpn_as/scripts/sacli
    --key "auth.ldap.0.users_base_dn" --value "{{ ldap_base_dn }}" ConfigPut
  when: >
    jsondata_config | json_query('\"auth.ldap.0.users_base_dn\"') != ldap_base_dn
- name: Set LDAP User attribute
  command: >
    /usr/local/openvpn_as/scripts/sacli
    --key "auth.ldap.0.uname_attr" --value sAMAccountName ConfigPut
  when: >
    jsondata_config | json_query('\"auth.ldap.0.uname_attr\"') != "sAMAccountName"
- name: Set LDAP Additional Requirement (Member of Filtering)
  command: >
    /usr/local/openvpn_as/scripts/sacli
    --key "auth.ldap.0.add_req" --value "{{ ldap_add_req }}" ConfigPut
  when: >
    jsondata_config | json_query('\"auth.ldap.0.add_req\"') != ldap_add_req
