---
- name: Check that the somefile.conf exists
  stat:
    path: "/etc/letsencrypt/live/{{ openvpnas_dns }}/cert.pem"
  register: pem_file
- name: Set certbot with AWS Route 53
  command: >
    /bin/certbot certonly --dns-route53 --non-interactive --agree-tos
    --email {{ certificate_email }} -d {{ openvpnas_dns }}
    --pre-hook 'service openvpnas stop' --post-hook 'service openvpnas start'
  when: not pem_file.stat.exists
- name: Create Symlink for SSL Certs
  file:
    src: "{{ item.src_app }}"
    dest: "{{ item.dst_app }}"
    state: link
  with_items:
    - { src_app: "/etc/letsencrypt/live/{{ openvpnas_dns }}/cert.pem", dst_app: "/usr/local/openvpn_as/etc/web-ssl/server.crt" }
    - { src_app: "/etc/letsencrypt/live/{{ openvpnas_dns }}/privkey.pem", dst_app: "/usr/local/openvpn_as/etc/web-ssl/server.key" }
    - { src_app: "/etc/letsencrypt/live/{{ openvpnas_dns }}/chain.pem", dst_app: "/usr/local/openvpn_as/etc/web-ssl/ca.crt" }
  when: pem_file.stat.exists
