---
- name: YUM | Install EPEL Repo
  yum:
    lock_timeout: 180
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  tags: epel-repo
- name: YUM | Install Certbot
  yum:
    lock_timeout: 180
    name: '{{ packages }}'
    state: present
  vars:
    packages:
    - certbot
    - python2-certbot
    - python2-certbot-dns-route53
    - python2-futures
- name: Check that the certbot-2 file exists
  stat:
    path: "usr/bin/certbot-2"
  register: certbot2_app
- name: Create Symlink for certbot-2 to certbot
  file:
    src: "usr/bin/certbot-2"
    dest: "/usr/bin/certbot"
    state: link
  when: certbot2_app.stat.exists
